accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/Login.html'), name='login'),
    #로직은 장고가 만들어둔 loginview를 가져오면 된다!, 그리고 아이디 비번 입력할 페이지만 만들면 된다! 이건 login.html로~ #

    path('logout/', LogoutView.as_view(), name='logout'),
    #장고가 만들어둔 logoutview를 가져오자!#

    path('create/', AccountCreateView.as_view(), name='create'),
    # 회원가입 페이지 연결 #

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    # 계정 상세페이지 연결 #

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    # 계정정보 수정 페이지 연결 #

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
    # 계정 탈퇴 페이지 연결 #
]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),    #admin은 관리자 페이지 - 장고에서 기본 제공해주는 것, 커스터마이징도 가능!
    path('accounts/', include('accountapp.urls')),    #빨간줄이 뜨면 Alt+enter을 눌러 도움을 받을 수 있음!
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #이렇게 해줘야 프로필 이미지가 나온다

likeapp/urls.py
from django.urls import path
from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

profileapp/urls.py
from django.urls import path
from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update')
]

accountapp/models.py
from django.db import models


# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #super()은 부모클래스의 메서드에 적급할 때 쓰는 메서드

        self.fields['username'].disabled = True
        #username이라는 fields를 찾아서 비활성화 하자!

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld
from articleapp.models import Article


@login_required
def hello_world(request):
    # print(type(request.POST))
    if request.method == "POST":   #method가 POST면~~
        temp = request.POST.get('hello_world_input')
        new_hello_world = HelloWorld()  #HelloWorld() 클래스 가져와서 new 만들기
        new_hello_world.text = temp  #models.py에 temp 넣기
        new_hello_world.save()  #models에 넣었으니 db에 저장
        return HttpResponseRedirect(reverse('accountapp:hello_world'))    #accountapp안에 hello_world 라우터에 재연결 해라! 그래야 Post 요청을 계속 반복 안함!
    else:
        hello_world_list = HelloWorld.objects.all()   #DB의 모든 데이터를 가져옴
        # hello_world_list.delete()
        return render(request, 'accountapp/hello_world.html',
                      context={'hello_world_list': hello_world_list})



class AccountCreateView(CreateView):    #AccountCreateView라는 이름의 class를 만들 건데, CreatView를 상속받아라!
    model = User
    form_class = UserCreationForm      #폼은 클래스로 만들건데 UserCreationForm이라는 class를 겨자다 쓸게!
    success_url = reverse_lazy('accountapp:hello_world')     #reverse와 무슨 차이냐면, class 안에서는 reverse_lazy를 해야함!
    template_name = 'accountapp/create.html'      #create.html 라우터를 만듬



class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'
    paginate_by = 20
    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list, **kwargs)


has_ownership = [login_required, account_ownership_required]
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):   #장고의 updateview 상속받기
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})



@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'  #삭제하고자하는 계정(객체)에 접근
    success_url = reverse_lazy('accountapp:hello_world')  #탈퇴가 완료되면 나오는 페이지
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}  {# 만들어둔 base.htmel을 불러온다. extends로~ #}

    <div class = "text-center mw-500 m-auto">  {# mw-500 css를 적용하고 좌우마진을 자동으로 준다 #}
        <div class="m-5">  {# 마진 #}
            <h4>Sign Up</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post">   {# post로 보내기 #}
                {% csrf_token %}    {# <- 이거를 작성해야 post 에러가 안뜬다 #}
                {% bootstrap_form form %}   {#이미 작성해두었기 때문에 form이라는 객체를 단순 출력만 해주면 된다#} {# -> bootstrap_form으로 변경 #}
                <div class="m-5">   {# 마진 #}
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}  {# 만들어둔 create.htmel을 배껴온다~ #}


{% block content %}

    <div class = "text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Quit</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}


{% block content %}

    <div class = "text-center mw-500 m-auto">
        <div class="m-5">
            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}"
                     class="profile_image m-4"
                     alt="profile image">  {# 프로필 이미지가 없을 때 보여줄 문구 #}
                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}   {# target_user가 나오게 ~ #}
                        {% if target_user == user %}
                        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                           class="material-icons round_button">
                            edit
                        </a>
                        {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
                <h2>
                    <a href="{% url 'profileapp:create' %}">
                        Create Profile
                    </a>
                </h2>
            {% endif %}
        </div>
         {% if user == target_user %}
        <div>
            <a href="{% url 'accountapp:update' pk=target_user.pk %}"
               class="material-icons round_button mx-2">
                settings
            </a>
            <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
               class="material-icons round_button mx-2">
                close
            </a>
        </div>
        {% endif %}
    </div>

    <div>
        {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}  {# base.htmel을 이 폴더에서 사용하겠다 확장하겠다! #}

{% block content %}

{#    <style>#}
{#        .testing {#}
{#            background-color: yellow;#}
{#            height: 48px;#}
{#            width: 48px;#}
{#            margin: 1.5rem;#}
{#            border-radius: .5rem;#}
{#        }#}
{#    </style>#}

    <div style="margin: 2rem; text-align: center;" >
        <h1 style="font-family: 'Russo One'; margin: 2rem;">
            hello world list
        </h1>

        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <div class="input-group mb-3 w-50 m-auto">
                <input type="text" class="form-control"
                       name="hello_world_input">
                <button class="btn btn-dark" type="submit">
                    Button
                </button>
            </div>
{#            <input type="text" name="hello_world_input">#}
{#            <input class="btn btn-dark rounded-pill px-4" type="submit">#}
        </form>

        {% if hello_world_list %}   {# hello_world_list가 있는지 확인 #}
            {% for hello_world in hello_world_list %}
                <h3>{{ hello_world.text }}</h3>
            {% endfor %}
        {% endif %}


{#    <div class="testing" style="display: block">block</div>   {#높이와 너비를 지정해도 공간을 부모의 너비 만큼 차지함#}
{#    <div class="testing" style="display: inline">inline</div>  {#높이를 지정해도 내용 글씨 만큰만 높이를 가짐#}
{#    <div class="testing" style="display: inline-block">inline-block</div>  {#높이와 너비 지정한 만큼#}
{#    <div class="testing" style="display: none">none</div>  {#시각화 되지 않음#}
{#    <div class="testing">default</div>  {#아무것도 안하면 부모의 너비만큼 공간 차지함#}

{#    <div class="testing" style="display: inline-block">block</div>  {# 아무것도 영향 안받음 #}
{#    <div class="testing" style="display: inline-block; width: 3rem; height: 3rem;">block</div>  {# 최상단 parent의 영향만 받음 #}
{#    <div class="testing" style="display: inline-block; width: 3em; height: 3em;">block</div>  {# 모든 parent 영향 받음#}
{#    <div class="testing" style="display: inline-block; width: 30%; height: 30%;">block</div>  {# 상자 사이즈 영향 받음#}

    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{# login 페이지는 create 페이지를 그대로 복사해와서 내용만 바꾸면 된다!#}

{% extends 'base.html' %}  {# 만들어둔 base.htmel을 불러온다. extends로~ #}
{% load bootstrap4 %}

{% block content %}

    <div class = "text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Login</h4>    {# sign up을 Login으로 변경 #}
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post">      {# create를 login으로 변경 #}
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}  {# 만들어둔 create.htmel을 배껴온다~ #}
{% load bootstrap4 %}

{% block content %}

    <div class = "text-center mw-500 m-auto">
        <div class="m-5">     {# 마진 #}
            <h4>Update Info</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                {# 무엇을 update 할 것인지 적어줘야한다 pk=target_user #}
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}