articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),    #admin은 관리자 페이지 - 장고에서 기본 제공해주는 것, 커스터마이징도 가능!
    path('accounts/', include('accountapp.urls')),    #빨간줄이 뜨면 Alt+enter을 눌러 도움을 받을 수 있음!
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #이렇게 해줘야 프로필 이미지가 나온다

likeapp/urls.py
from django.urls import path
from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models
from projectapp.models import Project


class Article(models.Model):  #게시글에 필요한 것들을 작성해보자~
    writer = models.ForeignKey(User,
                               on_delete=models.SET_NULL,
                               related_name='article',
                               null=True)  #User와의 연결고리
    project = models.ForeignKey(Project,
                                on_delete=models.SET_NULL, #게시판이 삭제되어도 게시글은 남아있음
                                related_name='article',
                                null=True)   #Project와의 연결고리
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

    like = models.IntegerField(default=0)

#프로필앱에서는 onetoone으로 1:1 매칭해야하지만,
#게시글은 한 유저가 여러가지 게시글을 작성할 수 있으므로,
#ForeignKey로 연결만 해주면 된다~

# 모델이 변화하면 migration, migrate해야한다!

templates/snippets/list_fragment.html
{% load static %}

    <style>
        .container {
            padding: 0;
            margin: 0 auto;
        }
        .container div {
          width: 45%;
          max-width: 250px;
          box-shadow: 0 0 .3rem grey;
          background-color: antiquewhite;
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 1rem;  {# 1rem은 16pixcel #}
          flex-direction: column;
        }
        .container img {
            width: 100%;
            border-radius: 1rem;
        }

    </style>

    <div class="container my-4">
        {% for article in article_list %}
            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}"
                         alt="">
                </a>
                <span class="m-2 NNS_B">{{ article.title }}</span>
            </div>
        {% endfor %}
    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>

    {% include 'snippets/pagination.html' %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-dark rounded-pill material-icons">
            brush
        </a>
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-outline-dark rounded-pill px-5">
            Create Article
        </a>
    </div>

templates/snippets/pagination.html
    <div class="text-center my-4">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"
                class = "btn btn-secondary rounded=pill">
               {{ page_obj.previous_page_number }}
            </a>
        {% endif %}
            <a href="#"
                class = "btn btn-dark rounded=pill NNS_B">
                {{ page_obj.number }}
            </a>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"
                class = "btn btn-secondary rounded=pill"> {# get방식 #}
                {{ page_obj.next_page_number }}
            </a>
        {% endif %}
    </div>