accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/Login.html'), name='login'),
    #로직은 장고가 만들어둔 loginview를 가져오면 된다!, 그리고 아이디 비번 입력할 페이지만 만들면 된다! 이건 login.html로~ #

    path('logout/', LogoutView.as_view(), name='logout'),
    #장고가 만들어둔 logoutview를 가져오자!#

    path('create/', AccountCreateView.as_view(), name='create'),
    # 회원가입 페이지 연결 #

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    # 계정 상세페이지 연결 #

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    # 계정정보 수정 페이지 연결 #

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
    # 계정 탈퇴 페이지 연결 #
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),    #admin은 관리자 페이지 - 장고에서 기본 제공해주는 것, 커스터마이징도 가능!
    path('accounts/', include('accountapp.urls')),    #빨간줄이 뜨면 Alt+enter을 눌러 도움을 받을 수 있음!
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #이렇게 해줘야 프로필 이미지가 나온다

likeapp/urls.py
from django.urls import path
from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

projectapp/urls.py
from django.urls import path
from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeapp/urls.py
from django.urls import path
from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR'">    {# 추가한 나눔 폰트를 body에 적용해준다! #}

    {% include 'header.html' %}

<hr>

{% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>
    </div>
{% endfor %}


    {% block content %}  #content라는 이름을 가진 block을 만들겠다!
    {% endblock %}

<hr>

    {% include 'footer.html' %}

</body>

</html>

templates/footer.html
<div style="text-align: center">

    <div class="footer_button">
        <spam>공지사항</spam>
        <spam>제휴문의</spam>
        <spam>서비스 소개</spam>

    </div>
    <div>
        <h6>Clinical Nutrition Times</h6>
    </div>

</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>

    {#  BOOTSTRAP LINK  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#  GOOGLE FONTS LINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

    {#  STATIC FILES LINK  #}
    <Link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  MATERIAL ICONS LINK  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">



    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center">

    <div class="header_logo" >
        <h1>Clinical Nutrition Times</h1>
        <h5>- 임상영양타임스 -</h5>
    </div>
    <div class="header_button">
        <span>
            <a href="{% url 'articleapp:list' %}">
                [전체 글]
            </a>
        </span>
        <span>
            <a href="{% url 'projectapp:list' %}">
                 [게시판]
            </a>
        </span>
        {% if user.is_authenticated %}
        <span>
            <a href="{% url 'subscribeapp:list' %}">
                [Subscription]
            </a>
        </span>
        {% endif %}

        {% if not user.is_authenticated %}

        <span>
            <a href="{% url 'accountapp:login' %}">
                [로그인]
            </a>
        </span>
        <span>
            <a href="{% url 'accountapp:create' %}">
                [회원가입]
            </a>
        </span>

        {% else %}
        <span>
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                [MyPage]
            </a>
        </span>
        <span>
            <a href="{% url 'accountapp:logout' %}">
                [로그아웃]
            </a>
        </span>

        {% endif %}

    </div>

</div>